server:
  port: 8989
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointment/**
          filters:
            - RewritePath=/appointment/(?<path>.*), /$\{path}

        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctor/**
          filters:
            - RewritePath=/doctor/(?<path>.*), /$\{path}

        - id: opd-service
          uri: lb://opd-service
          predicates:
            - Path=/opd/**
          filters:
            - RewritePath=/opd/(?<path>.*), /$\{path}

        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patient/**
          filters:
            - RewritePath=/patient/(?<path>.*), /$\{path}

#
#        - id: the-zecter.gomicroser
#          uri: lb://the-zecter.gomicroser
#          predicates:
#            - Path=/adolokak/**
#          filters:
#            - RewritePath=/adolokak/(?<path>.*), /$\{path}

#        - id: the-zecter.gomicroser
#          uri: lb://the-zecter.gomicroser
#          predicates:
#            - Path=/v1/adolokak/{segment}
#          filters:
#            - SetPath=/v1/{segment}
#            - RewritePath=/v1/adolokak/(?<path>.*), /$\{path}

#        - id: the-zecter.doctor-service
#          uri: lb://the-zecter.doctor-service
#          predicates:
#            - Path=/v1/doctor/**
#          filters:
#            - RewritePath=/v1/doctor/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7449/eureka

management:
  #  endpoint:
  #    gateway:
  #      enabled: true
  #    health:
  #      enabled: true
  #    mappings:
  #      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings,info,env

  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
